--- Entity relationship diagrams from foreign key metadata.
---
--- Output is Mermaid, so the result is a text file that renders in GitHub,
--- most documentation tools and Neovim markdown previewers — and diffs like
--- code, unlike a picture.

local client = require("dbclient.core.client")
local session = require("dbclient.session")

local M = {}

local function notify(message, level)
  vim.notify("DBClient: " .. message, level or vim.log.levels.INFO)
end

--- Mermaid is picky about identifiers; keep them alphanumeric.
local function safe(name)
  return (tostring(name):gsub("[^%w_]", "_"))
end

--- Mermaid's own type vocabulary is loose, so the database type is passed
--- through with the characters Mermaid cannot parse removed.
local function mermaid_type(type_name)
  return (tostring(type_name or "text"):gsub("[^%w_]", ""))
end

--- Build the diagram source.
---@param opts { schema: string, tables: table[], columns: table<string, table[]>, keys: table[] }
---@return string[]
function M.render(opts)
  local lines = {
    ("%%%% %s — generated by DBClient.nvim"):format(opts.schema),
    "erDiagram",
  }

  for _, entry in ipairs(opts.tables) do
    local columns = opts.columns[entry.name] or {}
    if #columns > 0 then
      table.insert(lines, ("    %s {"):format(safe(entry.name)))
      for _, column in ipairs(columns) do
        local marker = ""
        if column.key == "PRI" then
          marker = " PK"
        elseif opts.foreign_columns[entry.name .. "." .. column.name] then
          marker = " FK"
        end
        table.insert(
          lines,
          ("        %s %s%s"):format(mermaid_type(column.type), safe(column.name), marker)
        )
      end
      table.insert(lines, "    }")
    else
      table.insert(lines, ("    %s {"):format(safe(entry.name)))
      table.insert(lines, "    }")
    end
  end

  local seen = {}
  for _, key in ipairs(opts.keys) do
    -- `}o--||` reads "many optional on the left, exactly one on the right",
    -- which is what a nullable foreign key means.
    local edge = ("    %s }o--|| %s : %s"):format(
      safe(key.table),
      safe(key.ref_table),
      safe(key.column)
    )
    if not seen[edge] then
      seen[edge] = true
      table.insert(lines, edge)
    end
  end

  if #opts.keys == 0 then
    table.insert(lines, ("    %%%% no foreign keys found in %s"):format(opts.schema))
  end

  return lines
end

--- Generate a diagram for a schema and open it in a markdown buffer.
---@param opts { session_id?: string, schema: string, tables?: string[] }
function M.show(opts)
  local target = session.get(opts.session_id)
  if not target then
    return notify("no active connection", vim.log.levels.WARN)
  end

  notify("building the diagram...")

  client.async(function()
    local tables = session.tables(target.id, opts.schema)
    if opts.tables then
      tables = vim.tbl_filter(function(entry)
        return vim.tbl_contains(opts.tables, entry.name)
      end, tables)
    end

    local columns = {}
    local keys = {}
    local foreign_columns = {}

    for _, entry in ipairs(tables) do
      local ok, list = pcall(session.columns, target.id, opts.schema, entry.name)
      columns[entry.name] = ok and list or {}

      local keys_ok, table_keys = pcall(session.foreign_keys, target.id, opts.schema, entry.name)
      if keys_ok then
        for _, key in ipairs(table_keys) do
          table.insert(keys, {
            table = entry.name,
            column = key.column,
            ref_table = key.ref_table,
            ref_column = key.ref_column,
          })
          foreign_columns[entry.name .. "." .. key.column] = true
        end
      end
    end

    local diagram = M.render({
      schema = opts.schema,
      tables = tables,
      columns = columns,
      keys = keys,
      foreign_columns = foreign_columns,
    })

    local lines = {
      ("# %s"):format(opts.schema),
      "",
      ("%d tables, %d foreign keys."):format(#tables, #keys),
      "",
      "```mermaid",
    }
    vim.list_extend(lines, diagram)
    table.insert(lines, "```")

    local bufnr = require("dbclient.ui.buffer").scratch(
      ("dbclient://%s/%s.diagram.md"):format(target.name, opts.schema),
      { modifiable = true }
    )
    vim.bo[bufnr].filetype = "markdown"
    require("dbclient.ui.buffer").set_lines(bufnr, lines)
    require("dbclient.ui.buffer").show(bufnr, "vsplit")

    notify(("diagram ready: %d tables"):format(#tables))
  end, function(err)
    notify(err, vim.log.levels.ERROR)
  end)
end

return M
